### PR TITLE
Fix eager loading ancestors with scope

### LINKED ISSUE #250: Eager loading of ancestors not working when using scope
Eager loading of ancestors when working in scoped mode is not working, wrong ancestors (of other scopes) are attached to a node. Please let me know if you need more information to reproduce this.

### PR DESCRIPTION
**Pull request by kvas-damian**
Fixes https://github.com/lazychaser/laravel-nestedset/issues/250

### CODE REVIEW

File: src/BaseRelation.php [hunk 1]
```diff
@@ -141,11 +141,6 @@ public function getResults()
      */
     public function addEagerConstraints(array $models)
     {
-        // The first model in the array is always the parent, so add the scope constraints based on that model.
-        // @link https://github.com/laravel/framework/pull/25240
-        // @link https://github.com/lazychaser/laravel-nestedset/issues/351
-        optional($models[0])->applyNestedSetScope($this->query);
```
Comment (kvas-damian) [inline src/BaseRelation.php:147]: this was incorrect, when models were from different scopes

**Comment by kvas-damian** [comment]
@lazychaser any chance you can take a look on it?

**Comment by kvas-damian** [comment]
Thanks
